### ISSUE TITLE
[Might be working already?] Copy link button does not work on firefox

### ISSUE THREAD

**Issue by lubien** [lubien/sorteios#14]

**Comment by treblig-punisher** [comment]
Hey, can you provide a description? I'd like to help you solve this :D.

**Comment by lubien** [comment]
Sure! Join a room on Firefox and click on the copy button besides the link. It does not copy at all. Works on chrome!

**Comment by CalArcher** [comment]
@lubien Id love to fix this, can you assign it to me?

**Comment by treblig-punisher** [comment]
@lubien Alright, assign it to me and I'll get it done

**Comment by lubien** [comment]
In the spirit of first come first served @treblig-punisher came first asking questions so I'm assigning it to you

**Comment by treblig-punisher** [comment]
hey Lubien, I think I fixed the issue, how do I get you the fix? a pull request?

**Comment by lubien** [comment]
Yes, a PR is the way to go
