### ISSUE TITLE
Admin only: show a gif and delay showing the drawed person a bit

### ISSUE THREAD

**Issue by lubien** [lubien/sorteios#21]
When admin clicks on a draw button we should show a gif like:

![](https://media.tenor.com/wl_HyiAmtdkAAAAC/spin-lottery.gif)

Feel free to pick other better gif, this is the first I found.

Also delay a little bit before showing the person just so the gif can play a bit then show the name and hide the gif

**Comment by thauska** [comment]
Can I take this?

**Comment by lubien** [comment]
Sure

**Comment by dhonysilva** [comment]
I've submitted the PR #37 for this issue :)
