### ISSUE TITLE
Prize winner does not show on mobile

### ISSUE THREAD

**Issue by lubien** [lubien/sorteios#22]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/9121359/197291821-5956ed34-218e-4d4d-8090-e92330be5981.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/9121359/197291836-f028f990-9047-4927-9e0c-29d2b87a8f15.png">

Might be a css issue

**Comment by LucianeFernandesRoque** [comment]
can i take this issue?

**Comment by thauska** [comment]
Can I take this?

**Comment by lubien** [comment]
Sure!

**Comment by thauska** [comment]
PR created #23
