### ISSUE TITLE
Add "Logout" to the navbar

### ISSUE THREAD

**Issue by lubien** [lubien/sorteios#3]
Our session system is pretty simple, we just add `email` and `name` session keys. A logout button should clear all sessions and send you to the root `/` path

**Comment by its-kundan** [comment]
!assign

**Comment by Eazyisreal** [comment]
Kindly assign this to me @lubien

**Comment by lubien** [comment]
Since you commented first @its-kundan I'd give you priority on the assign assuming you still want, can you confirm?

**Comment by sumit-022** [comment]
I can work on this. Please assign me the issue

**Comment by lubien** [comment]
@Eazyisreal wanna take a stab at it?

Otherwise anyone is welcome to try, this issue is fairly important. First come first served

**Comment by Eazyisreal** [comment]
> @Eazyisreal wanna take a stab at it?
> 
> Otherwise anyone is welcome to try, this issue is fairly important. First come first served

I'll get it done
