### ISSUE TITLE
create room functionality does not work 

### ISSUE THREAD

**Issue by jeevikasirwani** [lubien/sorteios#48]
![Screenshot (258)](https://github.com/lubien/sorteios/assets/83456541/9dc6b566-1976-4f7f-9708-b028ec0c8389)

**Comment by lubien** [comment]
Thanks for reporting @jeevikasirwani 

We had some recent changes that made the UX slightly weird but you need to input the name and email to create a room.

I've created an issue to improve on this UX: https://github.com/lubien/sorteios/issues/43

I'll be closing this one in favor of that
